### ISSUE TITLE
When I open the app on my TI-84 Plus CE, the graphics look weird

### ISSUE THREAD

**Issue by Anonymous3-a** [MathisLav/GeometryDashCE#3]
Other then the graphics, it plays normally, but for now I must rely on the https://www.cemetech.net/downloads/files/1568/x2325 archive instead.

**Comment by MathisLav** [comment]
Not sure to understand what you mean. What is not working "normally" ?

**Comment by Anonymous3-a** [comment]
Working "normally" means that the graphics aren't all glitchy. Currently, this version has very messed up graphics.

**Comment by MathisLav** [comment]
Can you tell me more precisely what's wrong with the graphics? Is it possible for you to send me a screenshot or a photo of what's happening?

**Comment by Anonymous3-a** [comment]
TiLP won't let me take a screenshot while the app is running, but it basically spams the level with random blocks with glitchy textures.

**Comment by Anonymous3-a** [comment]
Update: I have a suspicion that I'm just using out-of-date levels. I'm going to see if that's what's wron
g.

**Comment by MathisLav** [comment]
That could make sense, let me know if it fixes your issue.

**Comment by Anonymous3-a** [comment]
It was the problem, sorry for wasting your time.

**Comment by egg-gitgud** [comment]
I'm having the same issues but, i can't play the first jump- the 'corruption' is the entire height of the screen... 
Update: this issue was only happening on 1/2 of the calculators i tested, so I'm not sure whets going on with that other one.

**Comment by MathisLav** [comment]
I can't help you with so few information. Are you sure you have the lattest version of geometrydash and its levels (available here https://tiplanet.org/forum/archives_voir.php?id=790041)? Do you have the lattest version of the LibLoad libraries (https://github.com/CE-Programming/libraries/releases/latest)?

If this still doesn't work, try resetting the calculator (put your programs in the archive first so you don't lose them). It may be an issue with some weird configuration of the screen or something like that.

And if it still doesn't work, can you give me a screenshot of what's happening ? (with CEmu or with a camera)
