### ISSUE TITLE
HOW WORK

### ISSUE THREAD

**Issue by GWDdoS** [MathisLav/GeometryDashCE#4]
I did the thingy with spasm on windows. no work why?

**Comment by MathisLav** [comment]
What are you trying to do ? If you want to play to Geometry dash, you may rather want to download the executable files here : https://tiplanet.org/forum/archives_voir.php?id=790041

Then transfer the files at the root of the archive into your calculator (except the README, ending with something like .8xv or .8xp). Finally, transfer to your calculator the levels you want. Some levels are available in the archive `levels` folder (the .8xv files).

Let me know if this fixes your problem.

**Comment by GWDdoS** [comment]
Where are the files

**Comment by MathisLav** [comment]
I told you exactly what to do to install the program, just follow the steps. I can't repeat what I've just said in my previous message.

The files are in the link I gave you. If you do not understand something, please ask me with more precision and politely.
