### ISSUE TITLE
Ti-84 plus?

### ISSUE THREAD

**Issue by Pixelzated** [MathisLav/GeometryDashCE#7]
Maybe this is a dumb question, but will this run on the non-color screen, and slightly thicker ti-84 plus?

**Comment by MathisLav** [comment]
Hello,

This program can only be used with eZ80 calculators that is Ti-84+CE and Ti-83 Premium CE calculators.

Unfortunately it cannot be used with monochrome Ti-84+ calcs, which are Z80 calculators.

**Comment by Pixelzated** [comment]
Ok
